services:
  db:
    image: postgres:16-alpine
    container_name: priceflow_db
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: priceflow_dev
    volumes:
      - pgdata:/var/lib/postgresql/priceflow_data
    ports:
      - "0.0.0.0:5432:5432"
 
volumes:
  pgdata: